name: Custom Branch Workflow

on:
  push:
    branches:
      - '3[0-9].[0-9].[0-9]{6}-submissions'

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from branch ${{ github.ref }}"
